/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentdatabase;

import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.crypto.*;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author mgrat
 */
public class Homepage extends javax.swing.JFrame {

   public static String f,ff,fn;
   public String Username="";
   Register rf = new Register();
  
   
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        browsebutton = new javax.swing.JButton();
        browsefield = new javax.swing.JTextField();
        Requestbutton = new javax.swing.JButton();
        getbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        Encydecyfield = new javax.swing.JTextField();
        encryptentry = new javax.swing.JButton();
        decryptentry = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home Page");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 5));

        browsebutton.setBackground(new java.awt.Color(0, 204, 204));
        browsebutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        browsebutton.setText("Browse");
        browsebutton.setFocusPainted(false);
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });

        browsefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Requestbutton.setBackground(new java.awt.Color(0, 204, 204));
        Requestbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Requestbutton.setText("Request Key");
        Requestbutton.setFocusPainted(false);
        Requestbutton.setFocusable(false);
        Requestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestbuttonActionPerformed(evt);
            }
        });

        getbutton.setBackground(new java.awt.Color(0, 204, 204));
        getbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        getbutton.setText("Get Key");
        getbutton.setFocusPainted(false);
        getbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setBackground(new java.awt.Color(0, 204, 204));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setFocusPainted(false);
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        Encydecyfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Encydecyfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncydecyfieldActionPerformed(evt);
            }
        });

        encryptentry.setBackground(new java.awt.Color(0, 204, 204));
        encryptentry.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        encryptentry.setText("Encrypt");
        encryptentry.setFocusPainted(false);
        encryptentry.setFocusable(false);
        encryptentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptentryActionPerformed(evt);
            }
        });

        decryptentry.setBackground(new java.awt.Color(0, 204, 204));
        decryptentry.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        decryptentry.setText("Decrypt");
        decryptentry.setFocusPainted(false);
        decryptentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptentryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(browsebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Requestbutton))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(getbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(browsefield))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(encryptentry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decryptentry, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Encydecyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browsefield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Requestbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Encydecyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptentry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptentry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestbuttonActionPerformed
         try
        {
            Login lf = new Login();
            this.Username = lf.username;
            if(Username == null || Username.isEmpty())
            {
                  JOptionPane.showMessageDialog(this, "Login first to proceed !");
                  dispose();
                  lf.show();         
            }
            else{
                System.out.println(Username);
                String key = "no key";
                String name = lf.username;
                String file = browsefield.getText();
                if(!file.equals("") || !file.equals("null"))
                {
                    String enc_dec = "Pending";
                    String sql ="insert into key_generator(name,filename, secret_key, enc_dec) values('"+name+"','"+file+"','"+key+"','"+enc_dec+"')";
                    rf.st.executeUpdate(sql);
                    Encydecyfield.setText("Updated to database !");
                }
                else{
                 JOptionPane.showMessageDialog(this, "Select the file !");
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_RequestbuttonActionPerformed

    private void getbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getbuttonActionPerformed
                if(f.equals("")){
                    JOptionPane.showMessageDialog(this,"Select correct format of file !");
                }  
                else{
                    try{
                        SecretKey key;
                        key =KeyGenerator.getInstance("Blowfish").generateKey();
                        String key1=key.toString().substring(key.toString().indexOf("@") + 2);
                        Encydecyfield.setText(key1);
                        String sql = "update key_generator set  secret_key = '"+key1+"' where filename = '"+f+"'";
                        rf.st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(this,"Key Generated !");
                    }catch (Exception e){
                        System.out.println(e.getMessage());
                    }
                }
    }//GEN-LAST:event_getbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
        JFileChooser jfc = new JFileChooser("./Files.pdf");
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            Homepage.f = jfc.getSelectedFile().getName(); // to get name of the file
            boolean extension = f.endsWith(".docx") || f.endsWith(".pdf") || f.endsWith(".pptx");
            browsefield.setText(f);

            if (extension) {
                Homepage.fn = jfc.getSelectedFile().getAbsolutePath();
                Homepage.ff = jfc.getSelectedFile().getPath();
            }
        }
    }//GEN-LAST:event_browsebuttonActionPerformed

    private void EncydecyfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncydecyfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncydecyfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void encryptentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptentryActionPerformed
         dispose();
        Encrypt en = new Encrypt();
        en.show();
    }//GEN-LAST:event_encryptentryActionPerformed

    private void decryptentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptentryActionPerformed
         dispose();
        Decrypt en = new Decrypt();
        en.show();
    }//GEN-LAST:event_decryptentryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Encydecyfield;
    private javax.swing.JButton Requestbutton;
    private javax.swing.JButton browsebutton;
    private javax.swing.JTextField browsefield;
    private javax.swing.JButton decryptentry;
    private javax.swing.JButton encryptentry;
    private javax.swing.JButton getbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbutton;
    // End of variables declaration//GEN-END:variables
}
